### ISSUE TITLE
 how to use relish in a express application

### ISSUE THREAD

**Issue by sergio11** [dialexa/relish#11]
Relish could be used on a express aplication with express validation middleware?

If it is not possible, Could you suggest me an alternative?

Greetings and thank you.

**Comment by galenandrew** [comment]
@sergio11 are you currently using Joi for validation in your express application?

**Comment by sergio11** [comment]
yes, I am developing a proyect based on this boilerplate  [KunalKapadia/express-mongoose-es6-rest-api](https://github.com/KunalKapadia/express-mongoose-es6-rest-api). In which it is used express-validation and JOI for API parameter validation.

how could employ relish here?

**Comment by galenandrew** [comment]
@sergio11 nice!

Relish (in it's current state) is tightly coupled to the Hapi framework and its route option's [`failAction`](http://hapijs.com/api#route-options). This means that Relish is not compatible with Express at the moment.

I would recommend checking out Joi's [`any.error`](https://github.com/hapijs/joi/blob/v9.0.4/API.md#anyerrorerr) option for setting custom errors on a Joi schema.
