### ISSUE TITLE
Update to support new paths in Joi 11

### ISSUE THREAD

**Issue by galenandrew** [dialexa/relish#15]
[Joi 11.0.0 introduced a breaking change](https://github.com/hapijs/joi/issues/1302) that changed how paths are represented in the error object.

[Hapi 16.6.1](https://github.com/hapijs/hapi/issues/3585) updated Joi to 11.0.0

Example of supporting new paths array is https://github.com/hapijs/hapi/pull/3582

**Comment by Satyricon** [comment]
having the same issue

**Comment by johannessjoberg** [comment]
Any updates towards this? :)

**Comment by yesiyan01** [comment]
Change line 19 of index.js from `key: i.path.split('.').pop(),` to `key: i.path.pop(),` should fix the issue.

**Comment by galenandrew** [comment]
@johannessjoberg @yesiyan01 Thanks for the bump here! Will look into feasibility of updating this week.

**Comment by johannessjoberg** [comment]
No worries! @galenandrew Thanks for a great tool and hope it turns out to be a feasible implementation :)

**Comment by johannessjoberg** [comment]
Hi again! Just posting a friendly reminder. If you need any help i'm happy to help out!

**Comment by galenandrew** [comment]
Sincere apologies for the delay getting this issue resolved and thank you for your patience. We will be updating the docs with more details, but relish@2.0.0 now supports Joi 11 paths in Hapi 16. We are working on a version with Hapi 17 support and hope to have that published soon.
